(executable
 (name main)
 (modules racionalno izraz solver parser pomozne metode vmesnik main))

(executable
 (name mainpy)
 (modules racionalno izraz solver parser pomozne metode vmesnik mainpy))

(executable
 (name testni_primeri)
 (modules racionalno izraz solver parser pomozne metode testni_primeri))